# Generated by Django 4.1.1 on 2022-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('saturacion', models.CharField(max_length=50)),
                ('stress', models.CharField(max_length=10)),
            ],
        ),
    ]
